Models/Item.cs
/*
' Copyright (c) 2018 Sample
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Web.Caching;
using DotNetNuke.Common.Utilities;
using DotNetNuke.ComponentModel.DataAnnotations;
using DotNetNuke.Entities.Content;

namespace SampleMVC.Modules.SampleMVC.Models
{
    [TableName("SampleMVC_Items")]
    //setup the primary key for table
    [PrimaryKey("ItemId", AutoIncrement = true)]
    //configure caching using PetaPoco
    [Cacheable("Items", CacheItemPriority.Default, 20)]
    //scope the objects to the ModuleId of a module on a page (or copy of a module on a page)
    [Scope("ModuleId")]
    public class Item
    {
        ///<summary>
        /// The ID of your object with the name of the ItemName
        ///</summary>
        public int ItemId { get; set; } = -1;
        ///<summary>
        /// A string with the name of the ItemName
        ///</summary>
        string _ItemName;
        public string ItemName { get => _ItemName;
            set => _ItemName = value;
        }

        ///<summary>
        /// A string with the description of the object
        ///</summary>
        public string ItemDescription { get; set; }

        ///<summary>
        /// An integer with the user id of the assigned user for the object
        ///</summary>
        public int AssignedUserId { get; set; }

        ///<summary>
        /// The ModuleId of where the object was created and gets displayed
        ///</summary>
        public int ModuleId { get; set; }

        ///<summary>
        /// An integer for the user id of the user who created the object
        ///</summary>
        public int CreatedByUserId { get; set; } = -1;

        ///<summary>
        /// An integer for the user id of the user who last updated the object
        ///</summary>
        public int LastModifiedByUserId { get; set; } = -1;

        ///<summary>
        /// The date the object was created
        ///</summary>
        public DateTime CreatedOnDate { get; set; } = DateTime.UtcNow;

        ///<summary>
        /// The date the object was updated
        ///</summary>
        public DateTime LastModifiedOnDate { get; set; } = DateTime.UtcNow;
    }
}

Controllers/ItemController.cs
/*
' Copyright (c) 2018 Sample
'  All rights reserved.
' 
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
' TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
' THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
' CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
' DEALINGS IN THE SOFTWARE.
' 
*/

using System;
using System.Linq;
using System.Web.Mvc;
using SampleMVC.Modules.SampleMVC.Components;
using SampleMVC.Modules.SampleMVC.Models;
using DotNetNuke.Web.Mvc.Framework.Controllers;
using DotNetNuke.Web.Mvc.Framework.ActionFilters;
using DotNetNuke.Entities.Users;
using DotNetNuke.Framework.JavaScriptLibraries;
using SampleMVC.Modules.SampleMVC.Mvc;

namespace SampleMVC.Modules.SampleMVC.Controllers
{
    [DnnHandleError]
    public class ItemController : DnnController
    {

        public ActionResult Delete(int itemId)
        {
            ItemManager.Instance.DeleteItem(itemId, ModuleContext.ModuleId);
            return RedirectToDefaultRoute();
        }

        public ActionResult Edit(int itemId = -1)
        {
            DotNetNuke.Framework.JavaScriptLibraries.JavaScript.RequestRegistration(CommonJs.DnnPlugins);

            var userlist = UserController.GetUsers(PortalSettings.PortalId);
            var users = from user in userlist.Cast<UserInfo>().ToList()
                        select new SelectListItem { Text = user.DisplayName, Value = user.UserID.ToString() };

            ViewBag.Users = users;

            var item = (itemId == -1)
                 ? new Item { ModuleId = ModuleContext.ModuleId }
                 : ItemManager.Instance.GetItem(itemId, ModuleContext.ModuleId);

            return View(item);
        }

        [HttpPost]
        [DotNetNuke.Web.Mvc.Framework.ActionFilters.ValidateAntiForgeryToken]
        public ActionResult Edit(Item item)
        {
            if (item.ItemId == -1)
            {
                item.CreatedByUserId = User.UserID;
                item.CreatedOnDate = DateTime.UtcNow;
                item.LastModifiedByUserId = User.UserID;
                item.LastModifiedOnDate = DateTime.UtcNow;

                ItemManager.Instance.CreateItem(item);
            }
            else
            {
                var existingItem = ItemManager.Instance.GetItem(item.ItemId, item.ModuleId);
                existingItem.LastModifiedByUserId = User.UserID;
                existingItem.LastModifiedOnDate = DateTime.UtcNow;
                existingItem.ItemName = item.ItemName;
                existingItem.ItemDescription = item.ItemDescription;
                existingItem.AssignedUserId = item.AssignedUserId;

                ItemManager.Instance.UpdateItem(existingItem);
            }

            return RedirectToDefaultRoute();
        }

        [MvcModule(route: "sampleAction", displayName: "Sample - item display / edit from template")]
        [ModuleAction(ControlKey = "Edit", TitleKey = "AddItem")]
        public ActionResult Index()
        {
            var items = ItemManager.Instance.GetItems(ModuleContext.ModuleId);
            ViewBag.items = items;
            ViewBag.settings = ItemManager.Instance.GetMvcSettings(ModuleContext);
            
            return View();
        }
    }
}

Views/Item/Edit.cshtml
@inherits DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<SampleMVC.Modules.SampleMVC.Models.Item>

@using System.Collections.Generic
@using DotNetNuke.Web.Mvc.Helpers

<div id="Item-@Dnn.ModuleContext.ModuleId">
    <div class="dnnForm dnnEditBasicSettings" id="dnnEditBasicSettings">
        <div class="dnnFormExpandContent dnnRight "><a href="#">@Dnn.LocalizeString("ExpandAll")</a></div>

        <h2 id="dnnSitePanel-BasicSettings" class="dnnFormSectionHead dnnClear">
            <a href="#" class="dnnSectionExpanded">@Dnn.LocalizeString("BasicSettings")</a>
        </h2>
        <fieldset>
            <div class="dnnFormItem">
                <div><label for="itemName">@Dnn.LocalizeString("lblName")</label></div>
                @Html.TextBoxFor(m => m.ItemName)
            </div>
            <div class="dnnFormItem">
                <div><label for="itemDescription">@Dnn.LocalizeString("lblDescription")</label></div>
                @Html.TextArea("itemDescription", Model.ItemDescription)
            </div>
            <div class="dnnFormItem">
                <div><label for="itemUser">@Dnn.LocalizeString("lblAssignedUser")</label></div>
                @Html.DropDownListFor(m => m.AssignedUserId, (IEnumerable<SelectListItem>)ViewBag.Users, "Choose...")
            </div>
            @Html.HiddenFor(m => m.ModuleId)
        </fieldset>
    </div>
    <button type="submit" class="dnnPrimaryAction">@Dnn.LocalizeString("Submit")</button>
    <a id="cancelEdit" href="#" class="dnnSecondaryAction">@Dnn.LocalizeString("Cancel")</a>
</div>

<script type="text/javascript">
    /*globals jQuery, window, Sys */
    (function($, Sys) {
        function dnnEditBasicSettings() {
            $('#dnnEditBasicSettings').dnnPanels();
            $('#dnnEditBasicSettings .dnnFormExpandContent a').dnnExpandAll({ expandText: '@Dnn.LocalizeString("ExpandAll")', collapseText: '@Dnn.LocalizeString("CollapseAll")', targetArea: '#dnnEditBasicSettings' });
        }

        $(function() {
            $('#cancelEdit').click(function() { dnnModal.closePopUp(false); });
            dnnEditBasicSettings();
            Sys.WebForms.PageRequestManager.getInstance().add_endRequest(function() {
                dnnEditBasicSettings();
            });
        });

    }(jQuery, window.Sys));
</script>

Views/Item/Index.cshtml
@*@inherits DotNetNuke.Web.Mvc.Framework.DnnWebViewPage<IEnumerable< SampleMVC.Modules.SampleMVC.Models.Item >>*@

@using System.Text.RegularExpressions
@using DotNetNuke.Web.Mvc.Helpers

<div id="Items-@Dnn.ModuleContext.ModuleId">
    <p><b>Sample Item Display</b></p>
    @if (ViewBag.items.Count == 0)
    {
        <p>@Dnn.LocalizeString("NoItems")</p>
    }
    else
    {
        <ul class="tm_tl">
            @foreach (var item in ViewBag.items)
            {
                <li class="tm_t">
                    <h3>@item.ItemName</h3>
                    <div class="tm_td">@item.ItemDescription</div>
                    @{
                        if (Dnn.ModuleContext.IsEditable)
                        {
                            <div>
                                <a href="@Url.Action("Edit", "Item", new {ctl = "Edit", itemId = item.ItemId})">@Dnn.LocalizeString("EditItem")</a>
                                <a href="@Url.Action("Delete", "Item", new {itemId = item.ItemId})">@Dnn.LocalizeString("DeleteItem")</a>
                            </div>
                        }
                    }
                </li>
            }
        </ul>
    }
    <p>
        Namespace: @ViewBag.settings.Namespace<br/>
        Controller: @ViewBag.settings.Controller<br/>
        Method: @ViewBag.settings.Method<br/>
    </p>
</div>